BlogWeb.API/Controllers/AdminBlogPostsController.cs
using BlogWeb.API.Data;
using BlogWeb.API.Models.Domains;
using BlogWeb.API.Models.Helpers;
using BlogWeb.API.Models.ViewModels;
using BlogWeb.API.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlogWeb.API.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostsController : Controller
    {
        private readonly ITagRepository tagrepo;
        private readonly BlogDBContext dbcon;
        private readonly IBlogPostRepository blogrepo;
        public AdminBlogPostsController(ITagRepository tagrepo, IBlogPostRepository blogrepo, BlogDBContext dbcon)
        {
            this.tagrepo = tagrepo;
            this.dbcon = dbcon;
            this.blogrepo = blogrepo;
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await tagrepo.GetAllAsync();
            AdminBlogPostViewModel model = new()
            {
                Tags = tags.Select(x => new SelectListItem
                {
                    Text = x.DisplayName,
                    Value = x.Id.ToString()
                })
            };
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Add(AdminBlogPostViewModel objModel)
        {
            var AllTags = new List<Tag>();
            foreach (var tag in objModel.SelectedTags)
            {
                var GuidId = Guid.Parse(tag);
                var NewTag = await tagrepo.GetAsync(GuidId);
                if (NewTag != null)
                {
                    AllTags.Add(NewTag);
                }
            }
            objModel.blogPostInfo.Tags = AllTags;
            await blogrepo.AddAsync(objModel.blogPostInfo);
            return RedirectToAction("List");
        }

        public async Task<IActionResult> List(string searchterm, string orderBy = "", int CurrentPage = 1)
        {
            using var transaction = await dbcon.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);
            searchterm = string.IsNullOrEmpty(searchterm) ? "" : searchterm.ToLower();
            BlogPostListViewModel ObjModel = new();
            ObjModel.NameSortOrder = string.IsNullOrEmpty(orderBy) ? "name_desc" : "";

            var IndexList = dbcon.BlogPosts.AsNoTracking().Include(_ => _.Tags).Where(_ => _.Visible == true
                        && _.Heading.ToLower().Contains(searchterm) || searchterm == null);

            switch (orderBy)
            {
                case "name_desc":
                    IndexList = IndexList.OrderByDescending(a => a.Heading);
                    break;
                default:
                    IndexList = IndexList.OrderBy(a => a.Heading);
                    break;
            }
            int TotalRecords = IndexList.Count();
            int PageSize = 5;
            int TotalPages = (int)Math.Ceiling((double)TotalRecords / PageSize);
            IndexList = IndexList.Skip((CurrentPage - 1) * PageSize).Take(PageSize);

            ObjModel.BlogPostList = IndexList;
            ObjModel.CurrentPage = CurrentPage;
            ObjModel.TotalPage = TotalPages;
            ObjModel.PageSize = PageSize;
            ObjModel.Term = searchterm;
            ObjModel.OrderBy = orderBy;
            await transaction.CommitAsync();
            return View(ObjModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid Id)
        {
            AdminBlogPostViewModel objModel = new();
            var result = await blogrepo.GetAsync(Id);
            var tagsFetch = await tagrepo.GetAllAsync();
            if (result != null)
            {
                objModel.blogPostInfo = result;
                objModel.Tags = tagsFetch.Select(_ => new SelectListItem
                {
                    Text = _.DisplayName,
                    Value = _.Id.ToString()
                });
                if (result.Tags != null)
                {
                    objModel.SelectedTags = result.Tags
                        .Select(_ => _.Id.ToString())
                        .ToArray();
                }
                return View(objModel);
            };
            return View(null);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(AdminBlogPostViewModel objModel)
        {
            var AllTags = new List<Tag>();
            foreach (var tag in objModel.SelectedTags)
            {
                var GuidId = Guid.Parse(tag);
                var NewTag = await tagrepo.GetAsync(GuidId);
                if (NewTag != null)
                {
                    AllTags.Add(NewTag);
                }
            }
            objModel.blogPostInfo.Tags = AllTags;
            var result = await blogrepo.EditAsync(objModel.blogPostInfo);
            if (result != null)
            {
                return RedirectToAction("List");
            }
            return RedirectToAction("Edit", new { id = objModel.blogPostInfo.Id });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid Id)
        {
            var result = await blogrepo.DeleteAsync(Id);
            if (result != null)
                return RedirectToAction("List");
            return RedirectToAction("Edit", new { id = Id });
        }
    }
}

BlogWeb.API/Controllers/AdminCategoryController.cs
using BlogWeb.API.Data;
using BlogWeb.API.Models.Helpers;
using BlogWeb.API.Models.ViewModels;
using BlogWeb.API.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogWeb.API.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminCategoryController : Controller
    {
        private readonly ICategoriesRepository categoryrepo;
        private readonly BlogDBContext dbcon;
        public AdminCategoryController(ICategoriesRepository categoryrepo, BlogDBContext dbcon)
        {
            this.categoryrepo = categoryrepo;
            this.dbcon = dbcon;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(CategoryViewModel objModel)
        {
            if (ModelState.IsValid)
            {
                await categoryrepo.AddAsync(objModel.CategoryModel);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Index(string searchterm, string orderBy = "", int CurrentPage = 1)
        {
            using var transaction = await dbcon.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);
            searchterm = string.IsNullOrEmpty(searchterm) ? "" : searchterm.ToLower();
            CategoryListViewModel ObjModel = new();
            ObjModel.CategoryList = new();
            ObjModel.NameSortOrder = string.IsNullOrEmpty(orderBy) ? "name_desc" : "";

            var IndexList = dbcon.Categorys.Include(_ => _.Tags).Where(_ => _.Name.ToLower().Contains(searchterm) || searchterm == null);

            switch (orderBy)
            {
                case "name_desc":
                    IndexList = IndexList.OrderByDescending(a => a.Name);
                    break;
                default:
                    IndexList = IndexList.OrderBy(a => a.Name);
                    break;
            }
            int TotalRecords = IndexList.Count();
            int PageSize = 5;
            int TotalPages = (int)Math.Ceiling((double)TotalRecords / PageSize);
            IndexList = IndexList.Skip((CurrentPage - 1) * PageSize).Take(PageSize);
            if (IndexList.Any())
            {
                foreach (var Item in IndexList)
                {
                    CategoryInfo newModel = new();
                    newModel.CategoryModel = Item;
                    newModel.TagsCount = Item.Tags.Count();
                    ObjModel.CategoryList.Add(newModel);
                }
            }
            ObjModel.CurrentPage = CurrentPage;
            ObjModel.TotalPage = TotalPages;
            ObjModel.PageSize = PageSize;
            ObjModel.Term = searchterm;
            ObjModel.OrderBy = orderBy;
            await transaction.CommitAsync();
            return View(ObjModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            CategoryViewModel objModel = new();
            var result = await categoryrepo.GetAsync(id);
            if (result != null)
            {
                objModel.CategoryModel = result;
                return View(objModel);
            }
            return View(null);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel objModel)
        {
            var result = await categoryrepo.EditAsync(objModel.CategoryModel);
            if (result != null)
                return RedirectToAction("Index");
            return RedirectToAction("Edit", new { id = objModel.CategoryModel.Id });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid Id)
        {
            var result = await categoryrepo.DeleteAsync(Id);
            if (result != null)
                return RedirectToAction("Index");
            return RedirectToAction("Edit", new { id = Id });
        }
    }
}

BlogWeb.API/Controllers/AdminTagsController.cs
using BlogWeb.API.Data;
using BlogWeb.API.Models.Helpers;
using BlogWeb.API.Models.ViewModels;
using BlogWeb.API.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogWeb.API.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminTagsController : Controller
    {
        private readonly ITagRepository tagrepo;
        private readonly BlogDBContext dbcon;
        public AdminTagsController(ITagRepository tagrepo, BlogDBContext dbcon)
        {
            this.tagrepo = tagrepo;
            this.dbcon = dbcon;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(TagViewModel objModel)
        {
            if (ModelState.IsValid)
            {
                await tagrepo.AddAsync(objModel.TagInfo);
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Index(string searchterm, string orderBy = "", int CurrentPage = 1)
        {
            searchterm = string.IsNullOrEmpty(searchterm) ? "" : searchterm.ToLower();
            TagListViewModel ObjModel = new();
            ObjModel.NameSortOrder = string.IsNullOrEmpty(orderBy) ? "name_desc" : "";

            var IndexList = dbcon.Tags.Where(_ => _.IsActive == true
                        && _.Name.ToLower().Contains(searchterm) || searchterm == null);

            switch (orderBy)
            {
                case "name_desc":
                    IndexList = IndexList.OrderByDescending(a => a.Name);
                    break;
                default:
                    IndexList = IndexList.OrderBy(a => a.Name);
                    break;
            }
            int TotalRecords = IndexList.Count();
            int PageSize = 5;
            int TotalPages = (int)Math.Ceiling((double)TotalRecords / PageSize);
            IndexList = IndexList.Skip((CurrentPage - 1) * PageSize).Take(PageSize);

            ObjModel.TagList = IndexList;
            ObjModel.CurrentPage = CurrentPage;
            ObjModel.TotalPage = TotalPages;
            ObjModel.PageSize = PageSize;
            ObjModel.Term = searchterm;
            ObjModel.OrderBy = orderBy;

            return View(ObjModel);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            TagViewModel objModel = new() { TagInfo = null };
            var result = await tagrepo.GetAsync(id);
            if (result != null)
            {
                objModel.TagInfo = result;
                return View(objModel);
            }
            return View(null);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(TagViewModel objModel)
        {
            var result = await tagrepo.EditAsync(objModel.TagInfo);
            if (result != null)
                return RedirectToAction("List");
            return RedirectToAction("Edit", new { id = objModel.TagInfo.Id });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid Id)
        {
            var result = await tagrepo.DeleteAsync(Id);
            if (result != null)
                return RedirectToAction("List");
            return RedirectToAction("Edit", new { id = Id });
        }
    }
}

BlogWeb.API/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signinManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ratul Koley Blogs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogWeb.API.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body id="homescreenbodytag">
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://i.imgur.com/f1mXQyx.png" alt="Ratul Blogs" width="30" height="24">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Development</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Technology</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Miscellaneous</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>
                        @if (signinManager.IsSignedIn(User) 
                            && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin Menu
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a style="font-weight:500;" class="dropdown-item" asp-area="" asp-controller="AdminCategory" asp-action="Index">Category Management</a></li>
                                    <li><a style="font-weight:500;" class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Index">Tags Management</a></li>
                                    <li><a style="font-weight:500;" class="dropdown-item" asp-area="" asp-controller="AdminBlogPosts" asp-action="List">Blog Management</a></li>
                                    <li><a style="font-weight:500;" class="dropdown-item" asp-area="" asp-controller="Account" asp-action="UserList">User Management</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                        @if (signinManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown" style="list-style: none; display: inline-block; margin-right: 10px;">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="text-decoration: none; color: #fff;">
                                    @User?.Identity?.Name
                                </a>
                                <ul class="dropdown-menu" style="min-width: 100px;">
                                    <li><a class="dropdown-item" asp-route-username="@User?.Identity?.Name" asp-area="" asp-controller="Account" asp-action="EditByName" style="text-decoration: none; font-weight:500; color: #000;">Account</a></li>
                                    <li><a class="dropdown-item" asp-route-username="@User?.Identity?.Name" asp-area="" asp-controller="Account" asp-action="ChangePassword" style="text-decoration: none;font-weight:500; color: #000;">Change Password</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Logout" style="text-decoration: none; font-weight:500; color: #000;">Logout <i class="fa fa-power-off"></i></a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown" style="list-style: none; display: inline-block; margin-right: 10px;">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="text-decoration: none; color: #fff;">
                                    Sign-In/Up
                                </a>
                                <ul class="dropdown-menu" style="min-width: 100px;">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Register" style="text-decoration: none;font-weight:500; color: #000;">Register</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Login" style="text-decoration: none;font-weight:500; color: #000;">Login</a></li>
                                </ul>
                            </li>
                        }
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>

                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-top:30px; ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="text-align: center; color:black">
        <hr style="width: 100%; border-top: 2px solid black; margin-top: 10px;" />
        <div class="container">
            <div class="social-links" style="margin-bottom:10px; font-size:25px;">
            <a style="color: #1F1F1F; text-decoration: none; margin: 0 10px;" href="https://github.com/RatulKoley"><i class='bx bxl-github'></i></a>
            <a style="text-decoration: none; margin: 0 10px;" href="https://www.linkedin.com/in/ratulkoley"><i class='bx bxl-linkedin'></i></a>
            <a style="color: #7285D1; text-decoration: none; margin: 0 10px;" href="https://discord.com/invite/NG6mHjnhTQ"><i class='bx bxl-discord-alt'></i></a>
            <a style="color: #FF0000; text-decoration: none; margin: 0 10px;" href="https://www.youtube.com/channel/UCZKi8INtrkNqudOWNkgA_2Q"><i class='bx bxl-youtube'></i></a>
            </div>
            &copy; 2023 - Ratul Koley Blogs - <a style="text-decoration:none;color:black;" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>